# Python for Data Analysis

Reference Book: [Python for Data Analysis, 3E](https://wesmckinney.com/book/)
<br>Reference Video: Bilibili Sun Xinghua Python Data Analysis

## 1. Numpy Basics

*Referece Chapter: Ch4*

In [1]:
import numpy as np
import copy
import pandas as pd
from IPython.display import display
import sys
import json
import requests
import re

### 1.1 Create np n-dim array

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print("arr1:")
print(arr1)
print(arr1.shape)
print(arr1.ndim)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)

print("arr2:")
print(arr2)
print(arr2.shape)
print(arr2.ndim)

arr1:
[6.  7.5 8.  0.  1. ]
(5,)
1
arr2:
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
2


In [3]:
arr1 = np.array([1,2,3,4,5])
print("arr1:")
print(arr1)
print(arr1.shape)
print(arr1.ndim)


arr2 = np.array(range(1,6))

print("arr2:")
print(arr2)
print(arr2.shape)
print(arr2.ndim)

arr3 = np.arange(1,6)

print("arr3:")
print(arr3)
print(arr3.shape)
print(arr3.ndim)

arr1:
[1 2 3 4 5]
(5,)
1
arr2:
[1 2 3 4 5]
(5,)
1
arr3:
[1 2 3 4 5]
(5,)
1


In [4]:
print(np.zeros(10))
print(np.ones_like(arr2))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1]


In [5]:
print(np.ones((3, 6)))
print(np.zeros_like(arr3))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0 0 0 0 0]


In [6]:
print(np.empty((2, 3, 2)))
print(np.full((21,2),-np.inf))
print(np.full_like(arr3.astype(np.float64),-np.inf))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]
 [-inf -inf]]
[-inf -inf -inf -inf -inf]


In [7]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [8]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.2 np.random

NumPy random number generator methods

| Method            | Description |
|------------------|-------------|
| `permutation`    | Return a random permutation of a sequence, or return a permuted range |
| `shuffle`        | Randomly permute a sequence in place |
| `uniform`        | Draw samples from a uniform distribution |
| `integers`       | Draw random integers from a given low-to-high range |
| `standard_normal`| Draw samples from a normal distribution with mean 0 and standard deviation 1 |
| `binomial`       | Draw samples from a binomial distribution |
| `normal`         | Draw samples from a normal (Gaussian) distribution |
| `beta`           | Draw samples from a beta distribution |
| `chisquare`      | Draw samples from a chi-square distribution |
| `gamma`          | Draw samples from a gamma distribution |
| `uniform`        | Draw samples from a uniform [0, 1) distribution |


In [9]:
rng = np.random.default_rng(seed=12345)
rng.uniform(0,1)

0.22733602246716966

In [10]:
np.random.randint(2)

0

### 1.3 reshape

In [11]:
print(np.arange(10).reshape(2,5))
print(np.arange(10).reshape(2,1,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]]


### 1.4  Index and Slicing

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

np.int64(5)

In [14]:
arr[5:8]

array([5, 6, 7])

In [15]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

> **Note:**  
> An important first distinction from Python's built-in lists is that **array slices are views on the original array**.  
> This means that the data is **not copied**, and any modifications to the view will be **reflected in the source array**.


In [16]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [17]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [18]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [19]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr3d[1, 0]

array([7, 8, 9])

In [22]:
np.linalg.norm(arr)

np.float64(12345.018752517146)

In [23]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

Boolean Indexing

### 1.5 Deep & Shallow Copy

In [24]:
#A shallow copy creates a new object, but it does not recursively copy nested objects. 
# Instead, it only copies references to them. This means that changes in the nested 
# objects of the original will also affect the copy.



original = [[1, 2, 3], [4, 5, 6]]
shallow = copy.copy(original)

# Modify nested list in original
original[0][0] = 99

print(original)  # [[99, 2, 3], [4, 5, 6]]
print(shallow)   # [[99, 2, 3], [4, 5, 6]]  (Affected!)


[[99, 2, 3], [4, 5, 6]]
[[99, 2, 3], [4, 5, 6]]


In [25]:
original[1]=[0,1,2]
print(original)  # [[99, 2, 3], [0, 1, 2]]
print(shallow)   # [[99, 2, 3], [4, 5, 6]]  (Not Affected!)

[[99, 2, 3], [0, 1, 2]]
[[99, 2, 3], [4, 5, 6]]


In [26]:
#A deep copy creates a completely independent clone of the original object, 
# including recursively copying all nested objects. This ensures that modifying the original 
# does not affect the copy.


deep = copy.deepcopy(original)

# Modify nested list in original
original[0][0] = 42

print(original)  # [[42, 2, 3], [0, 1, 2]]
print(deep)      # [[99, 2, 3], [0, 1, 2]]  (Not affected!)


[[42, 2, 3], [0, 1, 2]]
[[99, 2, 3], [0, 1, 2]]


#### DEEP and SHALLOW COPY in NUMPY


A shallow copy in NumPy means that the new array shares data with the original array. Modifying one affects the other.

```
Methods that create a shallow copy:
Slicing ([:])
Using numpy.view()
Assignment (=), which creates a reference, not a copy
```

```
Method that creates a deep copy:
Using numpy.copy()
```

## 2. Pandas Basics

In [27]:
pd1 = pd.DataFrame()
pd1.to_csv()

'""\n'

### 2.1 Fundamental Data Structures

#### 2.1.1 Series

In [28]:
obj =  pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [29]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [30]:
print(type(obj))
print(type(obj.array))

<class 'pandas.core.series.Series'>
<class 'pandas.core.arrays.numpy_.NumpyExtensionArray'>


Remarks:另一种思考 Series 的方式是将其视为一个固定长度、有序的字典，因为它是索引值到数据值的映射。它可以在很多可能使用字典的场景中使用



In [31]:
print("b" in obj2)
print("e" in obj2)

True
False


In [32]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

当您仅传递一个字典时，结果系列中的索引将根据字典的方法遵循键的顺序keys，这取决于键的插入顺序。您可以通过传递一个索引来覆盖此操作，该索引包含您希望它们在结果系列中出现的顺序的字典键：



In [34]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

#### 2.1.2 DataFrame

In [36]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [37]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
print(frame2)

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN


还可以使用特殊的iloc和loc属性通过位置或名称检索行（有关详细信息，请参阅稍后使用 loc 和 iloc 在 DataFrame 上进行选择）：

In [38]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [39]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

另一种常见的数据形式是字典的嵌套字典：

In [40]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
              "Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [41]:
print(frame3.transpose())
print(frame3.T)

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9
        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9


In [42]:
print(frame3.values)
print(frame3.to_numpy())
print(type(frame3.values))
print(type(frame3.to_numpy()))

[[1.5 nan]
 [1.7 2.4]
 [3.6 2.9]]
[[1.5 nan]
 [1.7 2.4]
 [3.6 2.9]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 2.2 Essential Functionalities

#### 2.2.1 Reindexing

| Argument   | Description |
|------------|------------|
| `labels`   | New sequence to use as an index. Can be an `Index` instance or any other sequence-like Python data structure. An `Index` will be used exactly as is without any copying. |
| `index`    | Use the passed sequence as the new index labels. |
| `columns`  | Use the passed sequence as the new column labels. |
| `axis`     | The axis to reindex, whether `"index"` (rows) or `"columns"`. The default is `"index"`. You can alternately do `reindex(index=new_labels)` or `reindex(columns=new_labels)`. |
| `method`   | Interpolation (fill) method; `"ffill"` fills forward, while `"bfill"` fills backward. |
| `fill_value` | Substitute value to use when introducing missing data by reindexing. Use `fill_value="missing"` (the default behavior) when you want absent labels to have null values in the result. |
| `limit`    | When forward filling or backfilling, the maximum size gap (in number of elements) to fill. |
| `tolerance` | When forward filling or backfilling, the maximum size gap (in absolute numeric distance) to fill for inexact matches. |
| `level`    | Match simple `Index` on level of `MultiIndex`; otherwise, select a subset of. |
| `copy`     | If `True`, always copy underlying data even if the new index is equivalent to the old index; if `False`, do not copy the data when the indexes are equivalent. |


In [43]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
print(obj)
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
print(obj2)

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64


In [44]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
print(obj3)
print(obj3.reindex(np.arange(6), method="ffill")
)

0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object


#### 2.2.2 Dropping Entries from an Axis

In [45]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
print(obj)
new_obj = obj.drop("c")
print(new_obj)

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64
a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64


In [46]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                 index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])


In [47]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [48]:
data.drop(index=["Colorado", "Ohio"])


,one,two,three,four
Utah,8,9,10,11
New York,12,13,14,15


In [49]:
data.drop(columns=["two"])


,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


#### 2.2.3 Indexing, Selection, and Filtering

In [50]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [51]:
print(obj["b"])
print(obj[1])

1.0
1.0


/var/folders/_5/ztyxm4j95854xqs2k_x83m1c0000gn/T/ipykernel_92605/107162252.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[1])


In [52]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [53]:
print(obj[["b", "a", "d"]]
)
print(obj[[1, 3]]
)

b    1.0
a    0.0
d    3.0
dtype: float64
b    1.0
d    3.0
dtype: float64


/var/folders/_5/ztyxm4j95854xqs2k_x83m1c0000gn/T/ipykernel_92605/3634886641.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[[1, 3]]


In [54]:
# The best way
print(obj.loc[["b", "a", "d"]])
print(type(obj.loc[["b", "a", "d"]]))

b    1.0
a    0.0
d    3.0
dtype: float64
<class 'pandas.core.series.Series'>


In [55]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                        index=["Ohio", "Colorado", "Utah", "New York"],
                        columns=["one", "two", "three", "four"])
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [56]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [57]:
data[["three", "one"]]

,three,one
Ohio,2,0
Colorado,6,4
Utah,10,8
New York,14,12


In [58]:
data[:2]


,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7


In [59]:
data[data["three"] > 5]


,one,two,three,four
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


**Selection on DataFrame with loc and iloc**

Like Series, DataFrame has special attributes loc and iloc for label-based and integer-based indexing, respectively. Since DataFrame is two-dimensional, you can select a subset of the rows and columns with NumPy-like notation using either axis labels (loc) or integers (iloc).

As a first example, let's select a single row by label:



In [60]:
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [61]:
data.loc[["Colorado", "New York"]]


,one,two,three,four
Colorado,4,5,6,7
New York,12,13,14,15


In [62]:
data.iloc[2]


one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [63]:
data.iloc[[2, 1]]


,one,two,three,four
Utah,8,9,10,11
Colorado,4,5,6,7


In [64]:
data.iloc[[1, 2], [3, 0, 1]]

,four,one,two
Colorado,7,4,5
Utah,11,8,9


In [65]:
data.loc[:"Utah", "two"]


Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [66]:
data.iloc[:, :3][data.three > 5]

,one,two,three
Colorado,4,5,6
Utah,8,9,10
New York,12,13,14


Indexing Options
<br>

| Type               | Notes |
|--------------------|-------|
| `df[column]`      | Select single column or sequence of columns from the DataFrame; special case conveniences: Boolean array (filter rows), slice (slice rows), or Boolean DataFrame (set values based on some criterion). |
| `df.loc[rows]`    | Select single row or subset of rows from the DataFrame by label. |
| `df.loc[:, cols]` | Select single column or subset of columns by label. |
| `df.loc[rows, cols]` | Select both row(s) and column(s) by label. |
| `df.iloc[rows]`   | Select single row or subset of rows from the DataFrame by integer position. |
| `df.iloc[:, cols]` | Select single column or subset of columns by integer position. |
| `df.iloc[rows, cols]` | Select both row(s) and column(s) by integer position. |
| `df.at[row, col]`  | Select a single scalar value by row and column label. |
| `df.iat[row, col]` | Select a single scalar value by row and column position (integers). |
| `reindex` method   | Select either rows or columns by labels. |


#### 2.2.4 Arithmetic and Data Alignment

In [67]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
         index=["a", "c", "e", "f", "g"])
print(s1)
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [68]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

The internal data alignment introduces missing values in the label locations that don’t overlap. Missing values will then propagate in further arithmetic computations.

In the case of DataFrame, alignment is performed on both rows and columns:



In [69]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                index=["Utah", "Ohio", "Texas", "Oregon"])
df1 + df2

,b,c,d,e
Colorado,NaN,NaN,NaN,NaN
Ohio,3.0,NaN,6.0,NaN
Oregon,NaN,NaN,NaN,NaN
Texas,9.0,NaN,12.0,NaN
Utah,NaN,NaN,NaN,NaN


Since the "c" and "e" columns are not found in both DataFrame objects, they appear as missing in the result. The same holds for the rows with labels that are not common to both objects.



**Arithmetic methods with fill values**

In [70]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list("abcde"))
df2.loc[1, "b"] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [71]:
df1 + df2

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,NaN
1,9.0,NaN,13.0,15.0,NaN
2,18.0,20.0,22.0,24.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [72]:
df1.add(df2, fill_value=0)

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,5.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


**Operations between DataFrame and Series**

In [73]:
arr = np.arange(12.).reshape((3, 4))

In [74]:
arr - arr[0]


array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [75]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                   columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
series = frame.iloc[0]
print(frame)
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


In [76]:
frame - series

,b,d,e
Utah,0.0,0.0,0.0
Ohio,3.0,3.0,3.0
Texas,6.0,6.0,6.0
Oregon,9.0,9.0,9.0


If an index value is not found in either the DataFrame’s columns or the Series’s index, the objects will be reindexed to form the union:



In [77]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
frame + series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


If you want to instead broadcast over the columns, matching on the rows, you have to use one of the arithmetic methods and specify to match over the index. For example:



In [78]:
series3 = frame["d"]

In [79]:
frame.sub(series3, axis="index")

,b,d,e
Utah,-1.0,0.0,1.0
Ohio,-1.0,0.0,1.0
Texas,-1.0,0.0,1.0
Oregon,-1.0,0.0,1.0


#### 2.2.5 Function Application and Mapping

In [80]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                   columns=list("bde"),
               index=["Utah", "Ohio", "Texas", "Oregon"])
frame

,b,d,e
Utah,0.561430,-1.846997,-0.778325
Ohio,0.545166,-1.587880,0.012952
Texas,0.049890,-0.103222,0.895817
Oregon,-0.252839,-0.528622,2.311200


Another frequent operation is applying a function on one-dimensional arrays to each column or row. DataFrame’s `apply` method does exactly this:


In [81]:
def f1(x):
    return x.max() - x.min()

In [82]:
frame.apply(f1,axis=0)

b    0.814270
d    1.743775
e    3.089526
dtype: float64

In [83]:
frame.apply(f1,axis=1)

Utah      2.408428
Ohio      2.133046
Texas     0.999039
Oregon    2.839822
dtype: float64

In [84]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [85]:
frame.apply(f2,axis=0)

,b,d,e
min,-0.252839,-1.846997,-0.778325
max,0.561430,-0.103222,2.311200


In [86]:
frame.apply(f2,axis=1)

,min,max
Utah,-1.846997,0.561430
Ohio,-1.587880,0.545166
Texas,-0.103222,0.895817
Oregon,-0.528622,2.311200


Element-wise Python functions can be used, too. Suppose you wanted to compute a formatted string from each floating-point value in frame. You can do this with `map`:

In [87]:
def my_format(x):
   return f"{x:.2f}"

In [88]:
frame.map(my_format)

,b,d,e
Utah,0.56,-1.85,-0.78
Ohio,0.55,-1.59,0.01
Texas,0.05,-0.10,0.90
Oregon,-0.25,-0.53,2.31


#### 2.2.6 Sorting and Ranking


In [89]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [90]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [91]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=["three", "one"],
                    columns=["d", "a", "b", "c"])
frame

,d,a,b,c
three,0,1,2,3
one,4,5,6,7


In [92]:
frame.sort_index(axis="columns")


,a,b,c,d
three,1,2,3,0
one,5,6,7,4


In [93]:
frame.sort_index(axis="index")


,d,a,b,c
one,4,5,6,7
three,0,1,2,3


In [94]:
frame.sort_index(axis="columns", ascending=False)

,d,c,b,a
three,0,3,2,1
one,4,7,6,5


In [95]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values(na_position="first")


1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

When sorting a DataFrame, you can use the data in one or more columns as the sort keys. To do so, pass one or more column names to `sort_values`:

In [96]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame.sort_values("b")


,b,a
2,-3,0
3,2,1
0,4,0
1,7,1


In [97]:
frame.sort_values(["a", "b"])

,b,a
2,-3,0
0,4,0
3,2,1
1,7,1


Ranking assigns ranks from one through the number of valid data points in an array, starting from the lowest value. The `rank` methods for Series and DataFrame are the place to look; by default, `rank` breaks ties by assigning each group the mean `rank`:



In [98]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [99]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [100]:
obj.rank(ascending=False)


0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [101]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                    "c": [-2, 5, 8, -2.5]})


In [102]:
frame.rank(axis="columns")

,b,a,c
0,3.0,2.0,1.0
1,3.0,1.0,2.0
2,1.0,2.0,3.0
3,3.0,2.0,1.0


In [103]:

obj.rank(method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

Tie-breaking methods with rank<br>
| Method   | Description |
|----------|------------|
| "average" | Default: assign the average rank to each entry in the equal group |
| "min"     | Use the minimum rank for the whole group |
| "max"     | Use the maximum rank for the whole group |
| "first"   | Assign ranks in the order the values appear in the data |
| "dense"   | Like method="min", but ranks always increase by 1 between groups rather than the number of equal elements in a group |


#### 2.2.7 Axis Indexes with Duplicate Labels

Up until now almost all of the examples we have looked at have unique axis labels (index values). While many pandas functions (like reindex) require that the labels be unique, it’s not mandatory. Let’s consider a small Series with duplicate indices:



In [104]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

### 2.3 Summarizing and Computing Descriptive Statistics

Descriptive and summary statistics
<br>

| Method       | Description |
|-------------|------------|
| `count`     | Number of non-NA values |
| `describe`  | Compute set of summary statistics |
| `min`, `max` | Compute minimum and maximum values |
| `argmin`, `argmax` | Compute index locations (integers) at which minimum or maximum value is obtained, respectively; not available on DataFrame objects |
| `idxmin`, `idxmax` | Compute index labels at which minimum or maximum value is obtained, respectively |
| `quantile`  | Compute sample quantile ranging from 0 to 1 (default: 0.5) |
| `sum`       | Sum of values |
| `mean`      | Mean of values |
| `median`    | Arithmetic median (50% quantile) of values |
| `mad`       | Mean absolute deviation from mean value |
| `prod`      | Product of all values |
| `var`       | Sample variance of values |
| `std`       | Sample standard deviation of values |
| `skew`      | Sample skewness (third moment) of values |
| `kurt`      | Sample kurtosis (fourth moment) of values |
| `cumsum`    | Cumulative sum of values |
| `cummin`, `cummax` | Cumulative minimum or maximum of values, respectively |
| `cumprod`   | Cumulative product of values |
| `diff`      | Compute first arithmetic difference (useful for time series) |
| `pct_change` | Compute percent changes |


#### 2.3.1 Correlation and Covariance

In [105]:
price = pd.read_pickle("examples/yahoo_price.pkl")

volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [106]:
display(price.head())

,AAPL,GOOG,IBM,MSFT
Date,,,,
2010-01-04,27.990226,313.062468,113.304536,25.884104
2010-01-05,28.038618,311.683844,111.935822,25.892466
2010-01-06,27.592626,303.826685,111.208683,25.733566
2010-01-07,27.541619,296.753749,110.823732,25.465944
2010-01-08,27.724725,300.709808,111.935822,25.641571


In [107]:
display(volume)

,AAPL,GOOG,IBM,MSFT
Date,,,,
2010-01-04,123432400,3927000,6155300,38409100
2010-01-05,150476200,6031900,6841400,49749600
2010-01-06,138040000,7987100,5605300,58182400
2010-01-07,119282800,12876600,5840600,50559700
2010-01-08,111902700,9483900,4197200,51197400
...,...,...,...,...
2016-10-17,23624900,1089500,5890400,23830000
2016-10-18,24553500,1995600,12770600,19149500
2016-10-19,20034600,116600,4632900,22878400


In [108]:
returns = price.pct_change()
returns

,AAPL,GOOG,IBM,MSFT
Date,,,,
2010-01-04,NaN,NaN,NaN,NaN
2010-01-05,0.001729,-0.004404,-0.012080,0.000323
2010-01-06,-0.015906,-0.025209,-0.006496,-0.006137
2010-01-07,-0.001849,-0.023280,-0.003462,-0.010400
2010-01-08,0.006648,0.013331,0.010035,0.006897
...,...,...,...,...
2016-10-17,-0.000680,0.001837,0.002072,-0.003483
2016-10-18,-0.000681,0.019616,-0.026168,0.007690
2016-10-19,-0.002979,0.007846,0.003583,-0.002255


In [109]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.49976361144151166)

In [110]:
returns.corr()


,AAPL,GOOG,IBM,MSFT
AAPL,1.000000,0.407919,0.386817,0.389695
GOOG,0.407919,1.000000,0.405099,0.465919
IBM,0.386817,0.405099,1.000000,0.499764
MSFT,0.389695,0.465919,0.499764,1.000000


In [111]:
returns.cov()

,AAPL,GOOG,IBM,MSFT
AAPL,0.000277,0.000107,0.000078,0.000095
GOOG,0.000107,0.000251,0.000078,0.000108
IBM,0.000078,0.000078,0.000146,0.000089
MSFT,0.000095,0.000108,0.000089,0.000215


#### 2.3.2 Unique Values, Value Counts, and Membership

In [112]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [113]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [114]:
obj.value_counts()


c    3
a    3
b    2
d    1
Name: count, dtype: int64

## 3. Data Loading, Storage, and File Formats

### 3.1 Reading and Writing Data in Text Format

#### 3.1.1 Reading Text Files in Pieces

When processing very large files or figuring out the right set of arguments to correctly process a large file, you may want to read only a small piece of a file or iterate through smaller chunks of the file.



In [115]:
pd.options.display.max_rows = 10

In [116]:
result = pd.read_csv("examples/ex6.csv")
result

,one,two,three,four,key
0,0.467976,-0.038649,-0.295344,-1.824726,L
1,-0.358893,1.404453,0.704965,-0.200638,B
2,-0.501840,0.659254,-0.421691,-0.057688,G
3,0.204886,1.074134,1.388361,-0.982404,R
4,0.354628,-0.133116,0.283763,-0.837063,Q
...,...,...,...,...,...
9995,2.311896,-0.417070,-1.409599,-0.515821,L
9996,-0.479893,-0.650419,0.745152,-0.646038,E
9997,0.523331,0.787112,0.486066,1.093156,K
9998,-0.362559,0.598894,-1.843201,0.887292,G


In [117]:
pd.read_csv("examples/ex6.csv", nrows=5)


,one,two,three,four,key
0,0.467976,-0.038649,-0.295344,-1.824726,L
1,-0.358893,1.404453,0.704965,-0.200638,B
2,-0.501840,0.659254,-0.421691,-0.057688,G
3,0.204886,1.074134,1.388361,-0.982404,R
4,0.354628,-0.133116,0.283763,-0.837063,Q


In [118]:
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)
type(chunker)

pandas.io.parsers.readers.TextFileReader

The TextFileReader object returned by pandas.read_csv allows you to iterate over the parts of the file according to the chunksize. For example, we can iterate over ex6.csv, aggregating the value counts in the "key" column, like so:



In [119]:
tot = pd.Series([], dtype='int64')
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)


In [120]:
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

#### 3.1.2 Writing Data to Text Format

In [121]:
data = frame
data

,b,a,c
0,4.3,0,-2.0
1,7.0,1,5.0
2,-3.0,0,8.0
3,2.0,1,-2.5


In [122]:
data.to_csv("examples/out.csv")

In [123]:
!cat examples/out.csv

,b,a,c
0,4.3,0,-2.0
1,7.0,1,5.0
2,-3.0,0,8.0
3,2.0,1,-2.5


In [124]:
data.to_csv(sys.stdout, sep="|")

|b|a|c
0|4.3|0|-2.0
1|7.0|1|5.0
2|-3.0|0|8.0
3|2.0|1|-2.5


#### 3.1.3 JSON (JavaScript Object Notation)

In [125]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [126]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

#### 3.1.4 Interacting with Web APIs

In [127]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
resp = requests.get(url)
resp.raise_for_status()
resp

<Response [200]>

It's a good practice to always call raise_for_status after using requests.get to check for HTTP errors.

The response object’s json method will return a Python object containing the parsed JSON data as a dictionary or list (depending on what JSON is returned):



In [128]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61054',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61054/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61054/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/61054/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/61054',
  'id': 2894543586,
  'node_id': 'PR_kwDOAA0YD86NU8T1',
  'number': 61054,
  'title': 'BUG: Fix return type of loc/iloc',
  'user': {'login': 'sanggon6107',
   'id': 68040183,
   'node_id': 'MDQ6VXNlcjY4MDQwMTgz',
   'avatar_url': 'https://avatars.githubusercontent.com/u/68040183?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/sanggon6107',
   'html_url': 'https://github.com/sanggon6107',
   'followers_url': 'https://api.github.com/users/sanggon6107/followers',
   'following_url': 'https://api.githu

Each element in data is a dictionary containing all of the data found on a GitHub issue page (except for the comments). We can pass data directly to pandas.DataFrame and extract fields of interest:



In [129]:
data[0]['title']

'BUG: Fix return type of loc/iloc'

In [130]:
issues = pd.DataFrame(data, columns=["number", "title",
                                   "labels", "state"])
issues

,number,title,labels,state
0,61054,BUG: Fix return type of loc/iloc,[],open
1,61053,DOC Fix Styler.to_latex to be in Writer column,[],open
2,61052,BUG: sometimes when using ~ and & operators fo...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
3,61051,"Renamed ""normalise"" to ""normalize""",[],open
4,61050,Adjust Docker File Key Value Format,[],open
...,...,...,...,...
25,61005,BUG: scatter and line matplotlib plots not com...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open
26,60999,ENH: Pass col_len to on_bad_lines callable,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
27,60998,ENH: Add `to_numeric_br()` function to convert...,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open
28,60997,BUG: fix read_json ignoring the dtype with the...,"[{'id': 49379259, 'node_id': 'MDU6TGFiZWw0OTM3...",open


## 4. Data Cleaning and Preparation

### 4.1 Handling Missing Data

In [131]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In pandas, we've adopted a convention used in the R programming language by referring to missing data as NA, which stands for not available. In statistics applications, NA data may either be data that does not exist or that exists but was not observed (through problems with data collection, for example). When cleaning up data for analysis, it is often important to do analysis on the missing data itself to identify data collection problems or potential biases in the data caused by missing data.

The built-in Python `None` value is also treated as NA:



In [132]:
pd.Series(["aardvark", np.nan, None, "avocado"]).isna()

0    False
1     True
2     True
3    False
dtype: bool

**Filtering Out Missing Data**

In [133]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data[data.notna()]


0    1.0
2    3.5
4    7.0
dtype: float64

With DataFrame objects, there are different ways to remove missing data. You may want to drop rows or columns that are all NA, or only those rows or columns containing any NAs at all. dropna by default drops any row containing a missing value:



In [134]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
               [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
2,NaN,NaN,NaN
3,NaN,6.5,3.0


In [135]:
data.dropna()

,0,1,2
0,1.0,6.5,3.0


In [136]:
data.dropna(how="all")

,0,1,2
0,1.0,6.5,3.0
1,1.0,NaN,NaN
3,NaN,6.5,3.0


Suppose you want to keep only rows containing at most a certain number of missing observations. You can indicate this with the thresh argument:



In [137]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan


In [138]:
df

,0,1,2
0,-1.431781,NaN,NaN
1,-0.176630,NaN,NaN
2,0.874553,NaN,-0.130543
3,0.452672,NaN,1.152793
4,-0.147709,0.431918,0.715913
5,-0.004387,-0.079425,-0.097455
6,1.096096,1.292823,0.023952


In [139]:
df.dropna()


,0,1,2
4,-0.147709,0.431918,0.715913
5,-0.004387,-0.079425,-0.097455
6,1.096096,1.292823,0.023952


In [140]:
df.dropna(thresh=2)

,0,1,2
2,0.874553,NaN,-0.130543
3,0.452672,NaN,1.152793
4,-0.147709,0.431918,0.715913
5,-0.004387,-0.079425,-0.097455
6,1.096096,1.292823,0.023952


**Filling In Missing Data**

Rather than filtering out missing data (and potentially discarding other data along with it), you may want to fill in the “holes” in any number of ways. For most purposes, the fillna method is the workhorse function to use. Calling fillna with a constant replaces missing values with that value:



In [141]:
df.fillna(0)

,0,1,2
0,-1.431781,0.000000,0.000000
1,-0.176630,0.000000,0.000000
2,0.874553,0.000000,-0.130543
3,0.452672,0.000000,1.152793
4,-0.147709,0.431918,0.715913
5,-0.004387,-0.079425,-0.097455
6,1.096096,1.292823,0.023952


In [142]:
#Calling fillna with a dictionary, you can use a different fill value for each column:
df.fillna({1: 0.5, 2: 0})


,0,1,2
0,-1.431781,0.500000,0.000000
1,-0.176630,0.500000,0.000000
2,0.874553,0.500000,-0.130543
3,0.452672,0.500000,1.152793
4,-0.147709,0.431918,0.715913
5,-0.004387,-0.079425,-0.097455
6,1.096096,1.292823,0.023952


In [143]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

,0,1,2
0,-0.188144,-0.188115,0.906085
1,1.088219,-0.329890,-0.129250
2,0.137775,NaN,-0.212727
3,-1.302730,NaN,0.894651
4,-0.626494,NaN,NaN
5,-0.194661,NaN,NaN


In [144]:
df.ffill()

,0,1,2
0,-0.188144,-0.188115,0.906085
1,1.088219,-0.329890,-0.129250
2,0.137775,-0.329890,-0.212727
3,-1.302730,-0.329890,0.894651
4,-0.626494,-0.329890,0.894651
5,-0.194661,-0.329890,0.894651


In [145]:
df.ffill(limit=2)

,0,1,2
0,-0.188144,-0.188115,0.906085
1,1.088219,-0.329890,-0.129250
2,0.137775,-0.329890,-0.212727
3,-1.302730,-0.329890,0.894651
4,-0.626494,NaN,0.894651
5,-0.194661,NaN,0.894651


In [146]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())


0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

### 4.2 Data Transformation

#### 4.2.1 Removing Duplicates

In [147]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                  "k2": [1, 1, 2, 3, 3, 4, 4]})
data

,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4
6,two,4


In [148]:
data.duplicated()


0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [149]:
data.drop_duplicates()


,k1,k2
0,one,1
1,two,1
2,one,2
3,two,3
4,one,3
5,two,4


Both methods by default consider all of the columns; alternatively, you can specify any subset of them to detect duplicates. Suppose we had an additional column of values and wanted to filter duplicates based only on the "k1" column:



In [150]:
data["v1"] = range(7)
data

,k1,k2,v1
0,one,1,0
1,two,1,1
2,one,2,2
3,two,3,3
4,one,3,4
5,two,4,5
6,two,4,6


In [151]:
data.drop_duplicates(subset=["k1"])

,k1,k2,v1
0,one,1,0
1,two,1,1


#### 4.2.2 Transforming Data Using a Function or Mapping

In [152]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                          "pastrami", "corned beef", "bacon",
                             "pastrami", "honey ham", "nova lox"],
                   "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

,food,ounces
0,bacon,4.0
1,pulled pork,3.0
2,bacon,12.0
3,pastrami,6.0
4,corned beef,7.5
5,bacon,8.0
6,pastrami,3.0
7,honey ham,5.0
8,nova lox,6.0


In [153]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [154]:
data["animal"] = data["food"].map(meat_to_animal)
data

,food,ounces,animal
0,bacon,4.0,pig
1,pulled pork,3.0,pig
2,bacon,12.0,pig
3,pastrami,6.0,cow
4,corned beef,7.5,cow
5,bacon,8.0,pig
6,pastrami,3.0,cow
7,honey ham,5.0,pig
8,nova lox,6.0,salmon


#### 4.2.3 Replacing Values

In [155]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

#### 4.2.4 Renaming Axis Indexes

In [156]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                  index=["Ohio", "Colorado", "New York"],
                 columns=["one", "two", "three", "four"])

In [157]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
New York,8,9,10,11


In [158]:
data.rename(index=str.title, columns=str.upper)

,ONE,TWO,THREE,FOUR
Ohio,0,1,2,3
Colorado,4,5,6,7
New York,8,9,10,11


In [159]:
data.rename(index={"OHIO": "INDIANA"},columns={"three": "peekaboo"})

,one,two,peekaboo,four
Ohio,0,1,2,3
Colorado,4,5,6,7
New York,8,9,10,11


#### 4.2.5 Discretization and Binning

In [160]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

The object pandas returns is a special Categorical object. The output you see describes the bins computed by pandas.cut. Each bin is identified by a special (unique to pandas) interval value type containing the lower and upper limit of each bin:



You can override the default interval-based bin labeling by passing a list or array to the labels option:



In [161]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins,labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

#### 4.2.6 Detecting and Filtering Outliers

In [162]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()


,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.030328,0.009577,-0.063843,0.054913
std,0.999938,1.019333,1.029574,1.015688
min,-2.975209,-3.029263,-3.342144,-3.136679
25%,-0.689554,-0.694029,-0.764383,-0.658276
50%,-0.029284,0.003740,-0.116579,0.022799
75%,0.625419,0.672538,0.625938,0.762860
max,3.429514,3.616309,2.864420,3.690000


In [163]:
col = data[2]
col

0     -2.249440
1      2.047306
2     -0.297131
3      0.674170
4     -0.524984
         ...   
995    0.491724
996    0.212822
997    0.812803
998   -1.215121
999    0.813264
Name: 2, Length: 1000, dtype: float64

In [164]:
col[col.abs() > 3]


71    -3.050970
81    -3.149498
266   -3.342144
Name: 2, dtype: float64

In [165]:
data[(data.abs() > 3).any(axis="columns")]


,0,1,2,3
71,-0.888872,-0.368848,-3.050970,1.179317
81,1.327562,-1.663458,-3.149498,0.283624
120,0.516423,-0.266786,-2.011327,-3.136679
203,0.119402,3.291584,0.090511,0.858216
266,-0.556230,-0.842294,-3.342144,0.916239
...,...,...,...,...
489,0.604690,1.467957,-1.282437,3.690000
544,0.079182,3.282938,0.214427,0.135991
550,-2.372659,-3.029263,-1.011510,-0.616970
732,0.373591,3.235563,0.581742,-0.871184


Values can be set based on these criteria. Here is code to cap values outside the interval –3 to 3 (clipping):

In [166]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

,0,1,2,3
count,1000.000000,1000.000000,1000.000000,1000.000000
mean,-0.030757,0.008179,-0.063300,0.054330
std,0.998541,1.014751,1.027955,1.012938
min,-2.975209,-3.000000,-3.000000,-3.000000
25%,-0.689554,-0.694029,-0.764383,-0.658276
50%,-0.029284,0.003740,-0.116579,0.022799
75%,0.625419,0.672538,0.625938,0.762860
max,3.000000,3.000000,2.864420,3.000000


#### 4.2.7 Permutation and Random Sampling

In [167]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
1,7,8,9,10,11,12,13
2,14,15,16,17,18,19,20
3,21,22,23,24,25,26,27
4,28,29,30,31,32,33,34


In [168]:
sampler = np.random.permutation(5)
sampler

array([0, 4, 3, 2, 1])

In [169]:
df.iloc[sampler]


,0,1,2,3,4,5,6
0,0,1,2,3,4,5,6
4,28,29,30,31,32,33,34
3,21,22,23,24,25,26,27
2,14,15,16,17,18,19,20
1,7,8,9,10,11,12,13


In [170]:
column_sampler = np.random.permutation(7)
df.iloc[:,column_sampler]

,0,2,3,5,1,4,6
0,0,2,3,5,1,4,6
1,7,9,10,12,8,11,13
2,14,16,17,19,15,18,20
3,21,23,24,26,22,25,27
4,28,30,31,33,29,32,34


#### 4.2.8 Computing Indicator/Dummy Variables

Another type of transformation for statistical modeling or machine learning applications is converting a categorical variable into a dummy or indicator matrix. If a column in a DataFrame has k distinct values, you would derive a matrix or DataFrame with k columns containing all 1s and 0s. pandas has a `pandas.get_dummies` function for doing this, though you could also devise one yourself. Let’s consider an example DataFrame:

In [171]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                 "data1": range(6)})
df

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [172]:
pd.get_dummies(df["key"], dtype=float)

,a,b,c
0,0.0,1.0,0.0
1,0.0,1.0,0.0
2,1.0,0.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0
5,0.0,1.0,0.0


In [173]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)
dummies

,key_a,key_b,key_c
0,0.0,1.0,0.0
1,0.0,1.0,0.0
2,1.0,0.0,0.0
3,0.0,0.0,1.0
4,1.0,0.0,0.0
5,0.0,1.0,0.0


In [174]:
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

,data1,key_a,key_b,key_c
0,0,0.0,1.0,0.0
1,1,0.0,1.0,0.0
2,2,1.0,0.0,0.0
3,3,0.0,0.0,1.0
4,4,1.0,0.0,0.0
5,5,0.0,1.0,0.0


### 4.3 String Manipulation

In [175]:
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [176]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [177]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [178]:
"::".join(pieces)


'a::b::guido'

In [179]:
"guido" in val


True

In [180]:
val.index(",")


1

In [181]:
val.find(":")


-1

Note that the difference between `find` and `index` is that `index` raises an exception if the string isn’t found (versus returning –1):

In [182]:
val.count(",")

2

In [183]:
val.replace(",", "::")

'a::b::  guido'

Python built-in string methods
<br>
| Method     | Description |
|------------|-------------|
| `count`    | Return the number of non-overlapping occurrences of a substring in the string. |
| `endswith` | Return `True` if the string ends with the specified suffix. |
| `startswith` | Return `True` if the string starts with the specified prefix. |
| `join`     | Use the string as a delimiter for concatenating a sequence of other strings. |
| `index`    | Return the starting index of the first occurrence of the substring; raises `ValueError` if not found. |
| `find`     | Return the position of the first occurrence of the substring; like `index`, but returns `-1` if not found. |
| `rfind`    | Return the position of the last occurrence of the substring; returns `-1` if not found. |
| `replace`  | Replace occurrences of a substring with another string. |
| `strip`, `rstrip`, `lstrip` | Trim whitespace, including newlines, from both sides, the right side, or the left side, respectively. |
| `split`    | Break the string into a list of substrings using a specified delimiter. |
| `lower`    | Convert all alphabetic characters to lowercase. |
| `upper`    | Convert all alphabetic characters to uppercase. |
| `casefold` | Convert characters to lowercase and normalize region-specific variations for better comparison. |
| `ljust`, `rjust` | Left-justify or right-justify the string, padding it with spaces or another fill character to ensure a minimum width. |


The regex describing one or more whitespace characters is \s+:



In [184]:
text = "foo    bar\t baz  \tqux"
re.split(r"\s+", text)


['foo', 'bar', 'baz', 'qux']

### 4.4 Categorical Data

pandas has a special Categorical extension type for holding data that uses the integer-based categorical representation or encoding. This is a popular data compression technique for data with many occurrences of similar values and can provide significantly faster performance with lower memory use, especially for string data.

Let's consider the example Series from before:



In [185]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                 'count': rng.integers(3, 15, size=N),
'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

,basket_id,fruit,count,weight
0,0,apple,11,1.564438
1,1,orange,5,1.331256
2,2,apple,12,2.393235
3,3,apple,6,0.746937
4,4,apple,5,2.691024
5,5,orange,12,3.767211
6,6,apple,10,0.992983
7,7,apple,11,3.795525


In [186]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [187]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [188]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [189]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

A useful trick to get a mapping between codes and categories is:



In [190]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [191]:
df['fruit'] = df['fruit'].astype('category')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype   
---  ------     --------------  -----   
 0   basket_id  8 non-null      int64   
 1   fruit      8 non-null      category
 2   count      8 non-null      int64   
 3   weight     8 non-null      float64 
dtypes: category(1), float64(1), int64(2)
memory usage: 456.0 bytes


Unless explicitly specified, categorical conversions assume no specific ordering of the categories. So the categories array may be in a different order depending on the ordering of the input data. When using from_codes or any of the other constructors, you can indicate that the categories have a meaningful ordering:



In [192]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

## 5. Data Wrangling: Join, Combine, and Reshape

In many applications, data may be spread across a number of files or databases, or be arranged in a form that is not convenient to analyze. This chapter focuses on tools to help combine, join, and rearrange data.

First, I introduce the concept of hierarchical indexing in pandas, which is used extensively in some of these operations. I then dig into the particular data manipulations. You can see various applied usages of these tools in Ch 13: Data Analysis Examples.

### 5.1 Hierarchical Indexing

In [193]:
data = pd.Series(np.random.uniform(size=9),
                  index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    0.633591
   2    0.305083
   3    0.319162
b  1    0.785678
   3    0.294428
c  1    0.874438
   2    0.690322
d  2    0.676357
   3    0.181231
dtype: float64

What you’re seeing is a prettified view of a Series with a MultiIndex as its index. The “gaps” in the index display mean “use the label directly above”:



In [194]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [195]:
data["b"]


1    0.785678
3    0.294428
dtype: float64

In [196]:
data["b":"c"]


b  1    0.785678
   3    0.294428
c  1    0.874438
   2    0.690322
dtype: float64

In [197]:
data.loc[["b", "d"]]


b  1    0.785678
   3    0.294428
d  2    0.676357
   3    0.181231
dtype: float64

Hierarchical indexing plays an important role in reshaping data and in group-based operations like forming a pivot table. For example, you can rearrange this data into a DataFrame using its unstack method:



In [198]:
data.unstack()


,1,2,3
a,0.633591,0.305083,0.319162
b,0.785678,NaN,0.294428
c,0.874438,0.690322,NaN
d,NaN,0.676357,0.181231


In [199]:
data.unstack().stack()


a  1    0.633591
   2    0.305083
   3    0.319162
b  1    0.785678
   3    0.294428
c  1    0.874438
   2    0.690322
d  2    0.676357
   3    0.181231
dtype: float64

With a DataFrame, either axis can have a hierarchical index:



In [200]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                      index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
                    columns=[["Ohio", "Ohio", "Colorado"],
                              ["Green", "Red", "Green"]])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [201]:
print(frame.index.nlevels)
print(frame.columns.nlevels)

2
2


In [202]:
frame.index.names = ["key1", "key2"]
frame.columns.names = ["state", "color"]
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

#### 5.1.1 Reordering and Sorting Levels

In [203]:
frame.swaplevel("key1", "key2")


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [204]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [205]:
frame.sort_index(level=1)


state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [206]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

#### 5.1.2 Summary Statistics by Level

In [207]:
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [208]:
frame.groupby(level="color", axis="columns").sum()


/var/folders/_5/ztyxm4j95854xqs2k_x83m1c0000gn/T/ipykernel_92605/1417732070.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color", axis="columns").sum()


color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

#### 5.1.3 Indexing with a DataFrame's columns

It’s not unusual to want to use one or more columns from a DataFrame as the row index; alternatively, you may wish to move the row index into the DataFrame’s columns. Here’s an example DataFrame:



In [209]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                      "c": ["one", "one", "one", "two", "two",
                            "two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})
frame

,a,b,c,d
0,0,7,one,0
1,1,6,one,1
2,2,5,one,2
3,3,4,two,0
4,4,3,two,1
5,5,2,two,2
6,6,1,two,3


In [210]:
frame2 = frame.set_index(["c", "d"])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [211]:
frame.set_index(["c", "d"], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [212]:
frame2.reset_index()

,c,d,a,b
0,one,0,0,7
1,one,1,1,6
2,one,2,2,5
3,two,0,3,4
4,two,1,4,3
5,two,2,5,2
6,two,3,6,1


### 5.2 Combining and Merging Datasets

#### 5.2.1 Database-Style DataFrame Joins

Merge or join operations combine datasets by linking rows using one or more keys. These operations are particularly important in relational databases (e.g., SQL-based). The `pandas.merge` function in pandas is the main entry point for using these algorithms on your data.


In [213]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                  "data1": pd.Series(range(7), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                  "data2": pd.Series(range(3), dtype="Int64")})

print(df1)
print(df2)

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2


In [214]:
pd.merge(df1, df2)

,key,data1,data2
0,b,0,1
1,b,1,1
2,a,2,0
3,a,4,0
4,a,5,0
5,b,6,1


Note that I didn’t specify which column to join on. If that information is not specified, pandas.merge uses the overlapping column names as the keys. It’s a good practice to specify explicitly, though:



In [215]:
pd.merge(df1, df2, on="key")


,key,data1,data2
0,b,0,1
1,b,1,1
2,a,2,0
3,a,4,0
4,a,5,0
5,b,6,1


In [216]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                      "data1": pd.Series(range(7), dtype="Int64")})
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})
pd.merge(df3, df4, left_on="lkey", right_on="rkey")

,lkey,data1,rkey,data2
0,b,0,b,1
1,b,1,b,1
2,a,2,a,0
3,a,4,a,0
4,a,5,a,0
5,b,6,b,1


In [217]:
pd.merge(df1, df2, how="outer")

,key,data1,data2
0,a,2,0
1,a,4,0
2,a,5,0
3,b,0,1
4,b,1,1
5,b,6,1
6,c,3,<NA>
7,d,<NA>,2


Different join types with the how argument
<br>
| Option       | Behavior |
|-------------|-----------------------------------------------------------|
| `how="inner"` | Use only the key combinations observed in both tables. |
| `how="left"`  | Use all key combinations found in the left table. |
| `how="right"` | Use all key combinations found in the right table. |
| `how="outer"` | Use all key combinations observed in both tables together. |


Many-to-many merges form the Cartesian product of the matching keys. Here’s an example:

In [218]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": pd.Series(range(6), dtype="Int64")})
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})

In [219]:
df1

,key,data1
0,b,0
1,b,1
2,a,2
3,c,3
4,a,4
5,b,5


In [220]:
df2

,key,data2
0,a,0
1,b,1
2,a,2
3,b,3
4,d,4


In [221]:
pd.merge(df1, df2, on="key", how="left")


,key,data1,data2
0,b,0,1
1,b,0,3
2,b,1,1
3,b,1,3
4,a,2,0
...,...,...,...
6,c,3,<NA>
7,a,4,0
8,a,4,2
9,b,5,1


In [222]:
pd.merge(df1, df2, how="inner")

,key,data1,data2
0,b,0,1
1,b,0,3
2,b,1,1
3,b,1,3
4,a,2,0
5,a,2,2
6,a,4,0
7,a,4,2
8,b,5,1
9,b,5,3


#### 5.2.2 Merging on Index


In some cases, the merge key(s) in a DataFrame will be found in its index (row labels). In this case, you can pass left_index=True or right_index=True (or both) to indicate that the index should be used as the merge key:



In [223]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                      "value": pd.Series(range(6), dtype="Int64")})
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])
pd.merge(left1, right1, left_on="key", right_index=True)

,key,value,group_val
0,a,0,3.5
1,b,1,7.0
2,a,2,3.5
3,a,3,3.5
4,b,4,7.0


#### 5.2.3 Concatenating Along an Axis

In [224]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [226]:
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")
s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")
s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")

In [ ]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

By default, pandas.concat works along axis="index", producing another Series. If you pass axis="columns", the result will instead be a DataFrame:

In [228]:
pd.concat([s1, s2, s3], axis="columns")


,0,1,2
a,0,<NA>,<NA>
b,1,<NA>,<NA>
c,<NA>,2,<NA>
d,<NA>,3,<NA>
e,<NA>,4,<NA>
f,<NA>,<NA>,5
g,<NA>,<NA>,6


In [ ]:
s4 = pd.concat([s1, s3])
pd.concat([s1, s4], axis="columns")

,0,1
a,0,0
b,1,1
f,<NA>,5
g,<NA>,6


In [230]:
pd.concat([s1, s4], axis="columns", join="inner")

,0,1
a,0,0
b,1,1


### 5.3 Reshaping and Pivoting

#### 5.3.1 Reshaping with Hierarchical Indexing

In [231]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                   columns=pd.Index(["one", "two", "three"],
                   name="number"))
data

number,one,two,three
state,,,
Ohio,0,1,2
Colorado,3,4,5


In [234]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [235]:
result.unstack()


number,one,two,three
state,,,
Ohio,0,1,2
Colorado,3,4,5


In [236]:
result.unstack(level=0)


state,Ohio,Colorado
number,,
one,0,3
two,1,4
three,2,5


#### 5.3.2 Pivoting “Long” to “Wide” Format

In [237]:
data = pd.read_csv("examples/macrodata.csv")
data

,year,quarter,realgdp,realcons,realinv,realgovt,realdpi,cpi,m1,tbilrate,unemp,pop,infl,realint
0,1959,1,2710.349,1707.4,286.898,470.045,1886.9,28.980,139.7,2.82,5.8,177.146,0.00,0.00
1,1959,2,2778.801,1733.7,310.859,481.301,1919.7,29.150,141.7,3.08,5.1,177.830,2.34,0.74
2,1959,3,2775.488,1751.8,289.226,491.260,1916.4,29.350,140.5,3.82,5.3,178.657,2.74,1.09
3,1959,4,2785.204,1753.7,299.356,484.052,1931.3,29.370,140.0,4.33,5.6,179.386,0.27,4.06
4,1960,1,2847.699,1770.5,331.722,462.199,1955.5,29.540,139.6,3.50,5.2,180.007,2.31,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2008,3,13324.600,9267.7,1990.693,991.551,9838.3,216.889,1474.7,1.17,6.0,305.270,-3.16,4.33
199,2008,4,13141.920,9195.3,1857.661,1007.273,9920.4,212.174,1576.5,0.12,6.9,305.952,-8.79,8.91
200,2009,1,12925.410,9209.2,1558.494,996.287,9926.4,212.671,1592.8,0.22,8.1,306.547,0.94,-0.71
201,2009,2,12901.504,9189.0,1456.678,1023.528,10077.5,214.469,1653.6,0.18,9.2,307.226,3.37,-3.19


In [238]:
data = data.loc[:, ["year", "quarter", "realgdp", "infl", "unemp"]]
data.head()


,year,quarter,realgdp,infl,unemp
0,1959,1,2710.349,0.00,5.8
1,1959,2,2778.801,2.34,5.1
2,1959,3,2775.488,2.74,5.3
3,1959,4,2785.204,0.27,5.6
4,1960,1,2847.699,2.31,5.2


In [239]:
periods = pd.PeriodIndex(year=data.pop("year"),
                         quarter=data.pop("quarter"),
                         name="date")
periods

/var/folders/_5/ztyxm4j95854xqs2k_x83m1c0000gn/T/ipykernel_92605/1359989538.py:1: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  periods = pd.PeriodIndex(year=data.pop("year"),


PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', name='date', length=203)

In [240]:
data.index = periods.to_timestamp("D")
data.head()

,realgdp,infl,unemp
date,,,
1959-01-01,2710.349,0.00,5.8
1959-04-01,2778.801,2.34,5.1
1959-07-01,2775.488,2.74,5.3
1959-10-01,2785.204,0.27,5.6
1960-01-01,2847.699,2.31,5.2


In [242]:
data = data.reindex(columns=["realgdp", "infl", "unemp"])
data.columns.name = "item"
data.head()


item,realgdp,infl,unemp
date,,,
1959-01-01,2710.349,0.00,5.8
1959-04-01,2778.801,2.34,5.1
1959-07-01,2775.488,2.74,5.3
1959-10-01,2785.204,0.27,5.6
1960-01-01,2847.699,2.31,5.2


In [243]:
long_data = (data.stack()
               .reset_index()
               .rename(columns={0: "value"}))


In [246]:
long_data[:10]


,date,item,value
0,1959-01-01,realgdp,2710.349
1,1959-01-01,infl,0.000
2,1959-01-01,unemp,5.800
3,1959-04-01,realgdp,2778.801
4,1959-04-01,infl,2.340
5,1959-04-01,unemp,5.100
6,1959-07-01,realgdp,2775.488
7,1959-07-01,infl,2.740
8,1959-07-01,unemp,5.300
9,1959-10-01,realgdp,2785.204


In [247]:
pivoted = long_data.pivot(index="date", columns="item",
                              values="value")
pivoted.head()

item,infl,realgdp,unemp
date,,,
1959-01-01,0.00,2710.349,5.8
1959-04-01,2.34,2778.801,5.1
1959-07-01,2.74,2775.488,5.3
1959-10-01,0.27,2785.204,5.6
1960-01-01,2.31,2847.699,5.2


### 5.4 Plotting and Visualization